on:
  schedule:
    - cron: '0 6 * * *' # run every morning at 6 AM

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Service health check
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://fso-cicd22.herokuapp.com/health
          max-attempts: 3
          retry-delay: 5s